#!/bin/bash -e

source $(dirname $0)/version
cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi

LINKFLAGS="-X github.com/rancher/support-bundle-kit/cmd.AppVersion=$VERSION
           -X github.com/rancher/support-bundle-kit/cmd.GitCommit=$COMMIT"

OS=$(echo "$PLATFORM" | cut -d'/' -f1)
ARCH=$(echo "$PLATFORM" | cut -d'/' -f2)

echo "PLATFORM: $PLATFORM"
echo "OS: $OS"
echo "ARCH: $ARCH"

if [ -n "$OS" ] && [ -n "$ARCH" ]; then
  CGO_ENABLED=0 GOOS=$OS GOARCH=$ARCH go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/support-bundle-kit
else
  # default for local development build
  CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/support-bundle-kit
fi

# non-go scripts
cp hack/* bin
