on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.5.8
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/${{ inputs.arch }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Git is not in Dapper container image. Add it manually for dirty check.
      - name: Add Git
        run: apk add -U git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run dapper
        run: dapper ci

      - name: Docker Publish Master ${{ inputs.arch }}
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          context: package
          dockerfile: package/Dockerfile
          build-args: |
            ARCH=${{ inputs.arch }}
            VERSION=test-${{ github.sha }}-head
          push: true
          tags: jk82421/support-bundle-kit:test-head-${{ inputs.arch }}