name: Tag Build and Publish

on:
  push:
    tags:
      - v*

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      config-path: ${{ github.ref_name }}
    secrets: inherit
